[package]
name = "finance-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.24.0"
reqwest = { version = "0.11.11", features = ["blocking"] }

